### PR TITLE
Create classification model for covid 19 radiography dataset

### PR DESCRIPTION
**Pull request by arnab031**
First Commit

### CODE REVIEW

**Comment by DARK-art108** [comment]
Please provide a sample of dataset @arnab031

**Comment by arnab031** [comment]
> Please provide a sample of dataset @arnab031

I have added a Sample Image of the dataset. Is it okay? @DARK-art108

**Comment by DARK-art108** [comment]
@all-contributors please add @arnab031  for Tutorials

**Comment by DARK-art108** [comment]
@all-contributors please add @arnab031 for Tutorials

**Comment by DARK-art108** [comment]
@all-contributors please add @arnab031 for Design

**Comment by DARK-art108** [comment]
@all-contributors please add @arnab031 for Design

**Pull request merged**
