### PR TITLE
update contributing.md

### PR DESCRIPTION
**Pull request by khareyash05**
Hey ! With reference to issue #23 
There is no loss of info in the file . I have just sorted things a bit and added few things such as
1. Squashing commits
2. Adding an upstream
3. Updating local and forked repo when changes are made in the upstream
Thank You 
@DARK-art108 have a look!

### CODE REVIEW

**Comment by khareyash05** [comment]
Hi @DARK-art108 could you pls ass a GSSOC label and a level label to the same

**Comment by DARK-art108** [comment]
@all-contributors please add @khareyash05  for Tutorials

**Comment by khareyash05** [comment]
Hi @DARK-art108  Could you pls add a level label and a GSSOC label to the PR as well because adding a level label to the PR is only being counted
Thanx!

**Comment by khareyash05** [comment]
Hi @DARK-art108 Could you pls add a level label and a GSSOC label to the PR as well because adding a level label to the PR is only being counted
Thanx!

**Pull request merged**
