### PR TITLE
Added face mask

### LINKED ISSUE #2: Mask Detection
I would like to add a project for mask detection. To be more precise, I would use datasets which contains multiple images and would detect whether the person is wearing mask or not. Then, determine the total number of person wearing and not wearing  mask.
I am a participant of GSSOC'21

### PR DESCRIPTION
**Pull request by sudipg4112001**
### Issue or bug fixed 
Fixes #2 

###Additional
- It is done using CNN
- I have added a the train, test and validation datasets in the dataset.rar file, because the datasets are large and couldn't be uploaded normally.

### CODE REVIEW

**Comment by Rishikeshrajrxl** [comment]
@DARK-art108, please review this PR, it looks good to me.

**Comment by DARK-art108** [comment]
@sudipg4112001 Also provide one live demo video or gif so that we can attach it to our Readme.md

**Comment by sudipg4112001** [comment]
Okay.. But, will the readme file made by me or should I only upload the gif ?

**Comment by DARK-art108** [comment]
Just provide a gif :)

**Comment by DARK-art108** [comment]
Add-in GDrive

**Comment by sudipg4112001** [comment]
Okay.. I will add it

**Comment by DARK-art108** [comment]
Then I will merge it automatically :)

**Comment by sudipg4112001** [comment]
I am providing an image because this PR fully works on images. It detects images and checks mask is present or not

**Comment by DARK-art108** [comment]
Yeah Sure provide an image

**Comment by sudipg4112001** [comment]
I have added to images in this PR. Do, review

**Review by DARK-art108 — APPROVED** [review]

**Comment by sudipg4112001** [comment]
Thanks

**Comment by DARK-art108** [comment]
@all-contributors please add @sudipg4112001  for Tutorials

**Pull request merged**
