### PR TITLE
GAN and CGAN architecture on MNIST data

### PR DESCRIPTION
**Pull request by ELITA04**
#38 

I have added notebooks for GANs and CGANs architecture on MNIST data. I have also updated the readme for the same.

Please review and let me know if any changes are required.

Thank you! :)

### CODE REVIEW

**Comment by DARK-art108** [comment]
@ELITA04 Thanks for Contributing :)

**Comment by DARK-art108** [comment]
@all-contributors please add @arnab031 for Tutorials

**Comment by DARK-art108** [comment]
@all-contributors please add @ELITA04  for Tutorials

**Comment by ELITA04** [comment]
Hello @DARK-art108,
Unfortunately, this PR hasn't been tagged as GSSOC21 with its level and as a result, the points haven't been updated, could you please do the same?

**Pull request merged**
